-- Tabela cliente (cria apenas se não existir)
CREATE TABLE IF NOT EXISTS cliente (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    contato character varying(255) NULL,
    created_at timestamp(6) with time zone NULL,
    elegivel_desconto boolean NULL,
    nome character varying(255) NOT NULL
);

DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints 
                   WHERE constraint_name = 'cliente_pkey' AND table_name = 'cliente') THEN
        ALTER TABLE cliente ADD CONSTRAINT cliente_pkey PRIMARY KEY (id);
    END IF;
END $$;

-- Tabela geracoes_parentais
CREATE TABLE IF NOT EXISTS geracoes_parentais (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    descricao character varying(255) NULL,
    nome character varying(255) NULL
);

DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints 
                   WHERE constraint_name = 'geracoes_parentais_pkey' AND table_name = 'geracoes_parentais') THEN
        ALTER TABLE geracoes_parentais ADD CONSTRAINT geracoes_parentais_pkey PRIMARY KEY (id);
    END IF;
END $$;

-- Tabela pato
CREATE TABLE IF NOT EXISTS pato (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6) with time zone NULL,
    filho_count integer NULL,
    nome character varying(255) NOT NULL,
    preco_categ character varying(255) NOT NULL,
    vendido boolean NULL,
    mae_id bigint NULL
);

DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints 
                   WHERE constraint_name = 'pato_pkey' AND table_name = 'pato') THEN
        ALTER TABLE pato ADD CONSTRAINT pato_pkey PRIMARY KEY (id);
    END IF;
END $$;

-- Tabela venda
CREATE TABLE IF NOT EXISTS venda (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6) with time zone NULL,
    data_venda timestamp(6) with time zone NOT NULL,
    desconto_aplicado numeric(12, 2) NULL,
    valor_total numeric(12, 2) NOT NULL,
    cliente_id bigint NOT NULL,
    vendedor_id bigint NOT NULL
);

DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints 
                   WHERE constraint_name = 'venda_pkey' AND table_name = 'venda') THEN
        ALTER TABLE venda ADD CONSTRAINT venda_pkey PRIMARY KEY (id);
    END IF;
END $$;

-- Tabela venda_pato
CREATE TABLE IF NOT EXISTS venda_pato (
    preco_unitario numeric(12, 2) NOT NULL,
    pato_id bigint NOT NULL,
    venda_id bigint NOT NULL
);

DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints 
                   WHERE constraint_name = 'venda_pato_pkey' AND table_name = 'venda_pato') THEN
        ALTER TABLE venda_pato ADD CONSTRAINT venda_pato_pkey PRIMARY KEY (pato_id, venda_id);
    END IF;
END $$;

-- Tabela vendedor
CREATE TABLE IF NOT EXISTS vendedor (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    cpf character varying(255) NOT NULL,
    created_at timestamp(6) with time zone NULL,
    matricula character varying(255) NOT NULL,
    nome character varying(255) NOT NULL
);

DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints 
                   WHERE constraint_name = 'vendedor_pkey' AND table_name = 'vendedor') THEN
        ALTER TABLE vendedor ADD CONSTRAINT vendedor_pkey PRIMARY KEY (id);
    END IF;
END $$;